Fix #577 - GUI: Choosing "Same file extension" results in "ERROR: Unknown option --match-with-extension."
sahib/rmlint pull request #578
Opened 2022-07-19 15:37 UTC by combs

2022-08-12 19:16 UTC, Cebtenzzre requested changes
docs/rmlint.1.rst should be updated with the new option names, it still refers to match-with-extension/no-match-with-extension. And a shorter commit title that doesn't end with "..." would be preferred.

2022-08-12 19:16 UTC, Cebtenzzre commented on gui/shredder/runner.py
> +        WITHOUT_EXTENSION: ['--no-match-extension']
Commit 89dc9015bda754b37cc12c06c9af7919690a2fe6 renamed only --match-with-extension and --no-match-with-extension. --match-without-extension is still a perfectly valid option, which only considers files to be duplicates if the part before the extension matches.

2022-08-14 21:21 UTC, combs commented
Happy to update `docs/rmlint.1.rst`, done.

I do feel it may be outside the initial scope of this PR (I am not personally changing the option name here; I am just fixing a bug in the GUI introduced by 89dc9015bda754b37cc12c06c9af7919690a2fe6 .) But happy to squash two birds (?) with one stone. 

Thank you!

2022-08-15 13:42 UTC, Cebtenzzre approved these changes

2025-03-08 09:56 UTC, vassilit commented
Already directly pushed to master in d526de1

2025-03-08 09:57 UTC, vassilit approved these changes

2025-03-08 09:57 UTC, vassilit commented
Already directly pushed to master in d526de1

2025-03-08 09:57 UTC, closed without merging